---
- name: Check OS version, User ID and hostnamectl
  hosts: all
  gather_facts: yes
  
  tasks:
#    - name: Get OS version
#      command: /etc/os-release
#      register: os_version
#      changed_when: false

#    - name: Show OS version
#      debug:
#        msg: "{{ os_version.stdout }}"

    - name: Get current user ID
      command: id
      register: user_id
      changed_when: false

    - name: Show User ID
      debug:
        msg: "User ID: {{ user_id.stdout }}"

    - name: Get the group info
      command: cat /etc/shadow
      register: groups_output

    - name: Show groups output
      debug:
        msg: "{{ groups_output.stdout }}"
