---
- name: Check OS version, User ID and hostnamectl
  hosts: pod-fqdn
  gather_facts: yes
  
  tasks:
    - name: Get the network info
      command: ifconfig
      register: net_output
      become: yes

    - name: Show network output
      debug:
        msg: "{{ net_output.stdout }}"
    
    - name: Get OS version
      command: cat /etc/os-release
      register: os_inf
      changed_when: false

    - name: Show OS version
      debug:
        msg: "{{ os_inf.stdout }}"

    - name: Get current user ID
      command: id
      register: user_id
      changed_when: false

    - name: Show User ID
      debug:
        msg: "User ID: {{ user_id.stdout }}"

    - name: Get the group info
      command: cat /etc/shadow
      register: groups_output
      become: yes

    - name: Show groups output
      debug:
        msg: "{{ groups_output.stdout }}"
